version: '3.8'

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password_here
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"  # Port mapping
    networks:
      - NetStori

  teststori:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /path/to/your/local/data:/app/data  # Specify the path to your local data
      - ./entrypoint.sh:/shell/entrypoint.sh 
    environment:
      - DEST_EMAIL=your_email@example.com
      - SMTP_SERVER=smtp.example.com
      - SMTP_PORT=587
      - SMTP_USERNAME=your_smtp_username
      - SMTP_PASSWORD=your_smtp_password
      - DB_HOST=192.168.xxx.xx
      - DB_USER=root
      - DB_PASSWORD=your_mysql_password
      - DB_DATABASE=transactions
    networks:
      - NetStori
    depends_on:
      - mysql
    command: ["/bin/sh", "-c", "sleep 30 && python3 ./src/main.py"]
   
    

networks:
  NetStori:
    driver: bridge
